### ISSUE TITLE
no module named recording

### ISSUE THREAD

**Issue by hunterzju** [ptrkrysik/examples#2]
I tried with the script /wideband_processing_demo/wideband_processing_demo.py file, but there are some mistakes:
1. in wideband_receiver.py , need to add 'import grgsm'
2. in wideband_receiver.py , there is no module called recording, i want to know if there is something wrong?
It would be nice if you can reply.

**Comment by ptrkrysik** [comment]
Hi @hunterzju. Thank you for pointing this. This issue was solved by #1 pull request and by #e4e387d commit.
